-- MySQL Script generated by MySQL Workbench
-- Sat Sep 14 00:30:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema site_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema site_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `site_db` ;
USE `site_db` ;

-- -----------------------------------------------------
-- Table `site_db`.`tbl_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_db`.`tbl_Users` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `User` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Hashed_Password` CHAR(45) NOT NULL,
  `Salt` CHAR(8) NOT NULL,
  PRIMARY KEY (`User_ID`),
  UNIQUE INDEX `SECONDARY` (`User` ASC) VISIBLE,
  UNIQUE INDEX `TERTIARY` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_db`.`tbl_Users_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_db`.`tbl_Users_copy1` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `User` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Hashed_Password` CHAR(45) NOT NULL,
  `Salt` CHAR(8) NOT NULL,
  PRIMARY KEY (`User_ID`),
  UNIQUE INDEX `SECONDARY` (`User` ASC) VISIBLE,
  UNIQUE INDEX `TERTIARY` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_db`.`tbl_Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_db`.`tbl_Messages` (
  `Message_ID` INT NOT NULL AUTO_INCREMENT,
  `Sent` DATETIME NOT NULL,
  `Body` TEXT NOT NULL,
  `Sender_ID` INT NOT NULL,
  `Recipient_ID` INT NOT NULL,
  PRIMARY KEY (`Message_ID`),
  UNIQUE INDEX `SECONDARY` (`Sent` ASC, `Sender_ID` ASC, `Recipient_ID` ASC) INVISIBLE,
  INDEX `fk_tbl_Messages_tbl_Users_idx` (`Sender_ID` ASC) VISIBLE,
  INDEX `fk_tbl_Messages_tbl_Users_copy11_idx` (`Recipient_ID` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_Messages_tbl_Users`
    FOREIGN KEY (`Sender_ID`)
    REFERENCES `site_db`.`tbl_Users` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_Messages_tbl_Users_copy11`
    FOREIGN KEY (`Recipient_ID`)
    REFERENCES `site_db`.`tbl_Users_copy1` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
